### ISSUE TITLE
error: return 404 error

### ISSUE THREAD

**Issue by fhefh2015** [pinceladasdaweb/imgur#3]
Failed to load resource: the server responded with a status of 400 (Bad Request)
imgur.min.js:2 Uncaught Error: 400 - Bad Request

**Comment by pinceladasdaweb** [comment]
What was the extent of the image you tried to climb that led to this error? As tested here and it's ok for me.

**Comment by fhefh2015** [comment]
@pinceladasdaweb 
The problem has been settled that the HongKong IP was blocked,  i don't know why.
